# Generated by Django 2.0.2 on 2018-03-03 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FangHao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameYuYueHao', models.CharField(max_length=200)),
                ('sheduleLoadTime', models.DateTimeField()),
                ('loadPoint', models.CharField(max_length=200)),
                ('beginTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('numHao', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QiangHao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weixinhao', models.CharField(max_length=200)),
                ('isactive', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('carplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booklist.CarPlan')),
                ('fanghao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booklist.FangHao')),
            ],
        ),
        migrations.CreateModel(
            name='XianChangDuiLie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loadPoint', models.CharField(max_length=200)),
                ('headNumber', models.CharField(max_length=200)),
                ('zhuangtai', models.CharField(max_length=20)),
                ('youxianji', models.CharField(max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('qianghao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booklist.QiangHao')),
            ],
        ),
    ]
