# Generated by Django 2.0.2 on 2018-03-04 02:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0002_fanghao_qianghao_xianchangduilie'),
    ]

    operations = [
        migrations.AddField(
            model_name='xianchangduilie',
            name='time_do',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 4, 2, 45, 13, 115399, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xianchangduilie',
            name='time_in',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 4, 2, 45, 16, 481650, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xianchangduilie',
            name='time_out',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 4, 2, 45, 18, 791193, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
