# Generated by Django 2.0.2 on 2018-03-04 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0003_auto_20180304_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qianghao',
            old_name='carplan',
            new_name='idf_carplan',
        ),
        migrations.RenameField(
            model_name='qianghao',
            old_name='fanghao',
            new_name='idf_fanghao',
        ),
        migrations.RenameField(
            model_name='xianchangduilie',
            old_name='qianghao',
            new_name='idf_qianghao',
        ),
        migrations.AddField(
            model_name='xianchangduilie',
            name='idf_carplan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booklist.CarPlan'),
            preserve_default=False,
        ),
    ]
