# Generated by Django 2.0.2 on 2018-03-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0004_auto_20180304_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xianchangduilie',
            name='idf_qianghao',
        ),
        migrations.AddField(
            model_name='xianchangduilie',
            name='id_s_qianghao',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
