# Generated by Django 2.0.2 on 2018-03-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0005_auto_20180304_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='juse',
            new_name='juese',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='urlcaoz',
            new_name='urlcaozuo',
        ),
        migrations.AlterField(
            model_name='carplan',
            name='convoyName',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='fanghao',
            name='nameYuYueHao',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='menu',
            name='text_beizhu',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='xianchangduilie',
            name='id_s_qianghao',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='xianchangduilie',
            name='time_do',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='xianchangduilie',
            name='time_in',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='xianchangduilie',
            name='time_out',
            field=models.DateTimeField(blank=True),
        ),
    ]
