# Generated by Django 2.0.2 on 2018-03-04 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0008_auto_20180304_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xianchangduilie',
            old_name='id_s_qianghao',
            new_name='idf_qianghao',
        ),
    ]
